CREATE TABLE cliente (
		id bigint generated by default as identity(start with 0),
		nome VARCHAR(50) NOT NULL,
		descrizione VARCHAR(256) NOT NULL,
		regitrazione TIMESTAMP NOT NULL with default,
		constraint pk_cliente primary key(id)
	);                   
		                 
CREATE UNIQUE INDEX cliente_uidx ON cliente (nome ASC);


CREATE TABLE server (
		id bigint generated by default as identity(start with 0),
		nome VARCHAR(128) NOT NULL,
		descrizione VARCHAR(256) NOT NULL,
		ip VARCHAR(64) NOT NULL,
		regitrazione TIMESTAMP NOT NULL with default,
		constraint pk_server primary key(id)
);

CREATE UNIQUE INDEX server_uidx ON server (nome ASC);

CREATE TABLE SOCIETA (
		id bigint generated by default as identity(start with 0),
		nome VARCHAR(64) NOT NULL UNIQUE,
		descrizione VARCHAR(256)  WITH DEFAULT,
		constraint pk_societa primary key(id)
	);
	
CREATE UNIQUE INDEX societa_uidx ON server (nome ASC);