CREATE TABLE CLIENTI (
		id bigint generated by default as identity(start with 0),
		CLIENTE VARCHAR(50) NOT NULL,
		DESCRIZIONE VARCHAR(256) NOT NULL,
		REGISTRAZIONE TIMESTAMP NOT NULL,
	);                   
		                 
INSERT INTO CLIENTI (CLIENTE,DESCRIZIONE,REGISTRAZIONE) 
SELECT OLD.CLIENTE,OLD.DESCRIZIONE,TIMESTAMP(OLD.DATA_IN,OLD.TIME_IN) FROM SEM.CLIENTIOLD OLD
                         
DROP TABLE SEM.CLIENTIOLD


select current_schema  
from   sysibm.sysdummy1
;